---
- hosts: all
  become: true

  roles:
    - { role: ./}

  vars:
       defaultsearch:
       nameserver: "8.8.8.8"
       dns_nameservers:
         - "8.8.8.8" # google dns
         - "8.8.4.4" # google dns

#- include: docker/integration-tests.yml

