---
# This playbook contains common plays that will be run on all nodes.
      
- name: Configure resolv file
  template: src=resolv.conf-{{ ansible_distribution }}.j2 dest=/etc/resolv.conf
  tags: configure

#needed for pidgin to work in file /etc/resolv.conf
#domain france.effix.fr

#TODO move 
#search misys.global.ad misys.global.ad. nt.france.effix.fr. france.effix.fr. effix.fr.
#inside
#/etc/resolvconf/resolv.conf.d/base  
      
- name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes

- name: Pushes new resolver configuration is resolver fails
  lineinfile: regexp="^nameserver " line="nameserver {{ nameserver }}" dest=/etc/resolv.conf
  when: ns|failed

- name: Checks if resolver is working properly with new nameserver
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes
  
- name: Restart dhclient
  command: dhclient
  when: ns|failed
    
- name: Checks if resolver is working properly with new nameserver
  command: host -t A ansible.cc
    
#- name: Final greeting
#  pause: prompt="Don't worry about all the red above; if you made it here, your Vagrant VMs are probably fine !
#    Please press [Enter]"
    
