---
# This playbook contains common plays that will be run on all nodes.

- name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes
  changed_when: false

#needed for pidgin to work in file /etc/resolv.conf
#domain nabla.test.fr

#TODO move
#search nabla.test.fr nabla.test.fr.
#inside
#/etc/resolvconf/resolv.conf.d/base

- name: Configure resolv file
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags: configure
  become: yes
  changed_when: false
  when: ns|failed

- name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes
  changed_when: false

- name: Pushes new resolver configuration is resolver fails
  lineinfile: regexp="^nameserver " line="nameserver {{ nameserver }}" dest=/etc/resolv.conf
  become: yes
  when: ns|failed

- name: Checks if resolver is working properly with new nameserver (1)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes
  changed_when: false

- name: Restart dhclient
  command: dhclient
  become: yes
  when: ns|failed

- name: Checks if resolver is working properly with new nameserver (2)
  command: host -t A ansible.cc
  ignore_errors: yes
  changed_when: false

#- name: Final greeting
#  pause: prompt="Don't worry about all the red above; if you made it here, your Vagrant VMs are probably fine !
#    Please press [Enter]"
